version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - .:/usr/src/aTES/apps/sso-api
      - ../schema-registry:/usr/src/aTES/apps/schema-registry
